### PR TITLE
Fix typo in contributing.md

### PR DESCRIPTION
**Pull request by geigerj0**
Just a tiny typo fix in the `contributing.md`.

### CODE REVIEW

**Review by ameowlia — APPROVED** [review]

**Comment by ameowlia** [comment]
@geigerj0 thank you for this fix. Can you sign the CLA before I merge?

**Comment by geigerj0** [comment]
> @geigerj0 thank you for this fix. Can you sign the CLA before I merge?

You are welcome 👍 . 

I signed it already, waiting for @stefanlay to approve it :)

**Comment by geigerj0** [comment]
@ameowlia do you know how I can get the necessary rights to see the Concourse build? 👼 Currently, I don't see any pipeline after granting`ci.funtime.lol` the permissions (reading e-mail & org).

**Comment by ameowlia** [comment]
Hi @geigerj0, only approvers to the networking area can see the concourse builds. Luckily this one passed 😉 . Merging.

**Pull request merged**
