### PR TITLE
Container outbound connection count limiting

### PR DESCRIPTION
**Pull request by IvanHristov98**
This PR is done as part of [silk-release#30](https://github.com/cloudfoundry/silk-release/issues/30). It introduces:
- an optional acceptance test to cover the app outbound connection rate limiting scenario that is turned off by default
- docs describing the use case that appears on large environments and how to configure the feature
- an enhancement to the acceptance test running guide

### CODE REVIEW

**Comment by geofffranks** [comment]
@IvanHristov98 can you rebase this off the latest develop branch and see if CI gets happier with it?

**Review by geofffranks — APPROVED** [review]

**Comment by geofffranks** [comment]
@IvanHristov98  I see the issue now. Since this was from before the codebases were reorganized as part of the go module conversions, even after the rebase, your new tests are in `src/test/acceptance`, but the rest were all moved to `src/code.cloudfoundry.org/test/acceptance`. Could you move them over + re-push?

**Comment by IvanHristov98** [comment]
@geofffranks moved it.

I have one more query to you. Since I don't have the permission to merge PRs could you merge this one and the other PR that is to `silk-release`. Thanks in advance.

**Comment by IvanHristov98** [comment]
It failed for some reason all over again but I don't know what since I don't have access to the pipeline.

**Comment by geofffranks** [comment]
Sorry, it's a new PR pipeline, we're still working out the kinks + access. Looks like it failed on a unit test for the tick app that failed to bind to a port. These have been flakey tests for us and we're trying to sort that out. In the mean time, I kicked it off again.

Once green, I'll merge this + the silk release PR together, than set CI up to run the new acceptance tests and hopefully it'll get released this week 🤞

**Pull request merged**
