### PR TITLE
fix: Update the security groups id data type from int to bigint

### PR DESCRIPTION
**Pull request by ZPascal**
**TODO:**
- [x] Fix the MySQL part
- [x] Fix the PostgreSQL part
- [x] Add new tests for the update case 

**Fix:**
#223

### CODE REVIEW

**Comment by ZPascal** [comment]
Hi @geofffranks, I've fixed the corresponding tests and placed new migration tests to validate the functionality in general. 

FYI: I'm not sure, why the easycla comment displays still a warning because the patched last [commit](https://github.com/cloudfoundry/cf-networking-release/pull/226/commits/2e6cec3e7ee0bf2ba083799cc375f5d4c042ece3) should be valid and without a typo inside the mail address.

**Comment by stefanlay** [comment]
> FYI: I'm not sure, why the easycla comment displays still a warning because the patched last [commit](https://github.com/cloudfoundry/cf-networking-release/pull/226/commits/2e6cec3e7ee0bf2ba083799cc375f5d4c042ece3) should be valid and without a typo inside the mail address.

I opened https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-19340

**Review by geofffranks — APPROVED** [review]

**Comment by geofffranks** [comment]
Approved - waiting for CI to run through tests

**Pull request merged**
